## Aggregates results from all validation suite reports into a single top-level summary.
class_name GodotDoctorSummaryReport
extends GodotDoctorReport

## Keys used in summary stats dictionaries returned by [method get_stats].
enum Stat {
	SUITE_COUNT,
	SCENES_VALIDATED,
	NODES_VALIDATED,
	RESOURCES_VALIDATED,
	INFO_COUNT,
	WARNING_COUNT,
	HARD_ERROR_COUNT,
	EFFECTIVE_ERROR_COUNT,
	WARNINGS_AS_ERRORS_COUNT,
	PASSED,
}

## The list of validation suite reports that make up this summary.
var suite_reports: Array[GodotDoctorValidationSuiteReport] = []


## Creates a new [GodotDoctorSummaryReport] from the given [param suite_reports].
func _init(suite_reports: Array[GodotDoctorValidationSuiteReport]) -> void:
	self.suite_reports = suite_reports


## Returns the total number of [constant ValidationCondition.Severity.INFO]-level messages
## across all suites.
## Prefer accessing this via [method get_stats] with [constant Stat.INFO_COUNT]
## to avoid unnecessary recomputation.
func get_num_infos() -> int:
	return suite_reports.reduce(
		func(total: int, suite_report: GodotDoctorValidationSuiteReport) -> int:
			return total + suite_report.get_num_infos(),
		0
	)


## Returns the total number of [constant ValidationCondition.Severity.WARNING]-level messages
## across all suites.
## Prefer accessing this via [method get_stats] with [constant Stat.WARNING_COUNT]
## to avoid unnecessary recomputation.
func get_num_warnings() -> int:
	return suite_reports.reduce(
		func(total: int, suite_report: GodotDoctorValidationSuiteReport) -> int:
			return total + suite_report.get_num_warnings(),
		0
	)


## Returns the total number of [constant ValidationCondition.Severity.ERROR]-level messages
## across all suites.
## Prefer accessing this via [method get_stats] with [constant Stat.HARD_ERROR_COUNT]
## to avoid unnecessary recomputation.
func get_num_errors() -> int:
	return suite_reports.reduce(
		func(total: int, suite_report: GodotDoctorValidationSuiteReport) -> int:
			return total + suite_report.get_num_errors(),
		0
	)


## Returns the total number of validation suites in this summary.
func _get_num_suites() -> int:
	return suite_reports.size()


## Returns the total number of scenes validated across all suites.
func _get_num_scenes() -> int:
	return suite_reports.reduce(
		func(total: int, suite_report: GodotDoctorValidationSuiteReport) -> int:
			return total + suite_report.get_scene_reports().size(),
		0
	)


## Returns the total number of nodes validated across all suites.
func _get_num_nodes() -> int:
	return suite_reports.reduce(
		func(total: int, suite_report: GodotDoctorValidationSuiteReport) -> int:
			return total + suite_report.get_num_nodes(),
		0
	)


## Returns the total number of resources validated across all suites.
func _get_num_resources() -> int:
	return suite_reports.reduce(
		func(total: int, suite_report: GodotDoctorValidationSuiteReport) -> int:
			return total + suite_report.get_num_resources(),
		0
	)


## Returns the total number of warnings that were treated as errors across all suites.
func _get_num_warnings_as_errors() -> int:
	return suite_reports.reduce(
		func(total: int, suite_report: GodotDoctorValidationSuiteReport) -> int:
			if suite_report.get_suite().treat_warnings_as_errors:
				return total + suite_report.get_num_warnings()
			return total,
		0
	)


## Returns the total number of effective errors
## (hard errors plus warnings promoted by
## [member GodotDoctorValidationSuite.treat_warnings_as_errors]).
func _get_num_effective_errors() -> int:
	return get_num_errors() + _get_num_warnings_as_errors()


## Returns [code]true[/code] if validation passed (no effective errors),
## or [code]false[/code] if validation failed (one or more effective errors).
func _passed() -> bool:
	return _get_num_effective_errors() == 0


## Returns a dictionary of aggregate summary stats keyed by [enum Stat].
## These stats are intended to be used for high-level reporting of validation results
## and should be accessed through the [Dictionary] generated by this method
## to prevent unnecessary recomputation of these values.
func get_stats() -> Dictionary:
	var stats: Dictionary = {
		Stat.SUITE_COUNT: _get_num_suites(),
		Stat.SCENES_VALIDATED: _get_num_scenes(),
		Stat.NODES_VALIDATED: _get_num_nodes(),
		Stat.RESOURCES_VALIDATED: _get_num_resources(),
		Stat.INFO_COUNT: get_num_infos(),
		Stat.WARNING_COUNT: get_num_warnings(),
		Stat.HARD_ERROR_COUNT: get_num_errors(),
		Stat.EFFECTIVE_ERROR_COUNT: _get_num_effective_errors(),
		Stat.WARNINGS_AS_ERRORS_COUNT: _get_num_warnings_as_errors(),
		Stat.PASSED: _passed(),
	}

	return stats


## Returns all validation suite reports in this summary.
func get_suite_reports() -> Array[GodotDoctorValidationSuiteReport]:
	return suite_reports
