## This script can be used in a Github Actions workflow to read the XML
## report generated by Godot Doctor and produce a markdown table summary
## on the Actions page.
##
## ℹ️ You probably want to copy this file to .github/workflows/scripts/ and
##    then run it from your workflow as described in the main addon README,
##    rather than running it directly from this examples directory.

import xml.etree.ElementTree as ET
import os
import sys

REPORT  = "tests/reports/godot_doctor_report.xml"
SUMMARY = os.environ["GITHUB_STEP_SUMMARY"]

SEVERITY_ICON = {
    "harderror": "🔴",
    "warning":   "⚠️",
    "info":      "ℹ️",
}

def attr_int(el, key):
    return int(el.attrib.get(key, 0))

def escape(text):
    return (text or "").strip().replace("|", "\\|")

# ── Parse ─────────────────────────────────────────────────────────────────────

try:
    tree = ET.parse(REPORT)
except FileNotFoundError:
    with open(SUMMARY, "a") as f:
        f.write("# 🩺 Godot Doctor\n\n> ⚠️ Report file not found.\n")
    sys.exit(0)

root   = tree.getroot()
suites = root.findall("testsuite")

has_promoted_warnings = any(
    msg.tag.lower() == "warning" and msg.attrib.get("type") == "promoted_to_error"
    for suite in suites
    for tc in suite.findall("testcase")
    for container in tc
    for msg in container
)

total_tests    = attr_int(root, "tests")
total_failures = attr_int(root, "failures")
total_harderrs = attr_int(root, "harderrors")
total_warnings = attr_int(root, "warnings")
total_infos    = attr_int(root, "infos")

overall_emoji  = "✅" if total_failures == 0 else "❌"
overall_label  = "All checks passed" if total_failures == 0 else f"{total_failures} check(s) failed"

lines = []

# ── Title ─────────────────────────────────────────────────────────────────────

lines.append("# 🩺 Godot Doctor Summary\n")
lines.append(f"**{overall_emoji} {overall_label}**\n")
if has_promoted_warnings:
    lines.append("> ⚠️ Warnings are treated as errors. Any warning will be reported as a failure.\n")

# ── Totals ────────────────────────────────────────────────────────────────────

lines.append("## Totals\n")
lines.append("| Status | Checks | 🔴 Errors | ⚠️ Warnings | ℹ️ Infos |")
lines.append("|:------:|:------:|:---------:|:-----------:|:--------:|")
lines.append(
    f"| {overall_emoji} | {total_tests} | {total_harderrs} | {total_warnings} | {total_infos} |"
)
lines.append("")

# ── Suites overview ───────────────────────────────────────────────────────────

lines.append("## Suites\n")
lines.append("| Suite | Status | Checks | 🔴 Errors | ⚠️ Warnings | ℹ️ Infos |")
lines.append("|-------|:------:|:------:|:---------:|:-----------:|:--------:|")

for suite in suites:
    s_name     = suite.attrib.get("name", "?")
    s_tests    = attr_int(suite, "tests")
    s_failures = attr_int(suite, "failures")
    s_harderrs = attr_int(suite, "harderrors")
    s_warnings = attr_int(suite, "warnings")
    s_infos    = attr_int(suite, "infos")
    s_status   = "✅ pass" if s_failures == 0 else "❌ fail"
    lines.append(
        f"| `{s_name}` | {s_status} | {s_tests} | {s_harderrs} | {s_warnings} | {s_infos} |"
    )

lines.append("")

# ── Results by suite ──────────────────────────────────────────────────────────

lines.append("## Results by suite\n")

for suite in suites:
    suite_path = suite.attrib.get("path", suite.attrib.get("name", "?"))
    lines.append(f"### `{suite_path}`\n")

    testcases = suite.findall("testcase")

    # ── Results by file ───────────────────────────────────────────────────────

    lines.append("#### Results by file\n")
    lines.append("| File | Type | Status | Checks | 🔴 Errors | ⚠️ Warnings | ℹ️ Infos |")
    lines.append("|------|:----:|:------:|:------:|:---------:|:-----------:|:--------:|")

    for tc in testcases:
        tc_name     = tc.attrib.get("name", "?")
        tc_type     = tc.attrib.get("type", "")
        tc_tests    = attr_int(tc, "tests")
        tc_failures = attr_int(tc, "failures")
        tc_harderrs = attr_int(tc, "harderrors")
        tc_warnings = attr_int(tc, "warnings")
        tc_infos    = attr_int(tc, "infos")
        tc_status   = "✅ pass" if tc_failures == 0 else "❌ fail"
        lines.append(
            f"| `{tc_name}` | {tc_type} | {tc_status} | {tc_tests} | {tc_harderrs} | {tc_warnings} | {tc_infos} |"
        )

    suite_tests_total    = attr_int(suite, "tests")
    suite_failures_total = attr_int(suite, "failures")
    suite_harderrs_total = attr_int(suite, "harderrors")
    suite_warnings_total = attr_int(suite, "warnings")
    suite_infos_total    = attr_int(suite, "infos")
    suite_status_total   = "✅ pass" if suite_failures_total == 0 else "❌ fail"
    lines.append(
        f"| **Total** | - | {suite_status_total} | {suite_tests_total} | {suite_harderrs_total} | {suite_warnings_total} | {suite_infos_total} |"
    )

    lines.append("")

    # ── Messages ──────────────────────────────────────────────────────────────

    # Collect every message across all testcases in this suite
    all_messages = []  # (tc_name, container_path, severity, text)
    for tc in testcases:
        tc_name = tc.attrib.get("name", "?")
        for container in tc:
            container_path = container.attrib.get("path",
                             container.attrib.get("name", "?"))
            for msg in container:
                severity = msg.tag.lower()
                all_messages.append((tc_name, container_path, severity, msg.text))

    lines.append("#### Messages\n")

    if not all_messages:
        lines.append("_No messages reported._\n")
    else:
        lines.append("| File | Node / Resource | Severity | Message |")
        lines.append("|------|-----------------|:--------:|---------|")
        for (tc_name, container_path, severity, text) in all_messages:
            icon  = SEVERITY_ICON.get(severity, "❓")
            lines.append(
                f"| `{tc_name}` | `{escape(container_path)}` | {icon} | {escape(text)} |"
            )
        lines.append("")

# ── Write ─────────────────────────────────────────────────────────────────────

with open(SUMMARY, "a") as f:
    f.write("\n".join(lines) + "\n")
